version: '2'
services:
  cashregister:
    image: drgeb/ansible_target:latest
    container_name: store_oraclepos_cashregister
    hostname: cashregister
    domainname: drgeb.com
    expose:
      - "22"
    links:
      - storeserver:oretail
    volumes:
      - /Volumes/lucky/Users/drgeb/Programming/sandbox/oretail/upload:/srv/download
  storeserver:
    image: drgeb/storeserver:latest
    container_name: store_oraclepos_server
    hostname: storeserver
    domainname: drgeb.com
    expose:
      - "22"
      - "1300"
    links:
      - database:storedb
      - messaging:storemq
    privileged: true
  database:
    image: drgeb/oracle12c
    container_name: store_database_server
    hostname: storedb
    domainname: drgeb.com
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    expose:
      - "1521"
      - "22"
    ports:
      - "1521:1521"
    environment:
      - CONTAINER=docker
    privileged: true
    cap_add:
      - sys_admin
  messaging:
    image: drgeb/mq
    container_name: store_mq_server
    hostname: storemq
    domainname: drgeb.com
    expose:
      - "1414"
      - "22"
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
  ansible_playbook:
    image: drgeb/ansible_playbook
    links:
      - cashregister
      - storeserver
      - database:storedb
      - messaging:storemq
    volumes:
      - ./files/ssh/ansible_vault:/root/.ssh/ansible_vault
      - ./files/ssh/id_rsa:/root/.ssh/id_rsa
      - ./files/ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
      - ~/.ansible/roles:/ansible/playbooks/roles
      - ~/.ansible/library:/ansible/library
      - .:/ansible/playbooks
